image: ubuntu:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE_ECR: "058264278815.dkr.ecr.eu-central-1.amazonaws.com/thehackathon"
  DOCKER_IMAGE_DOCKER_HUB: "thedoctor1121/ghotel-app"

before_script:
  - apt-get update && apt-get install -y python3 python3-pip python3-venv docker.io  # Update package list and install Python, pip, venv, and Docker
  - python3 -m venv venv                        # Create a virtual environment
  - source venv/bin/activate                    # Activate the virtual environment
  - pip install awscli                          # Install AWS CLI in the virtual environment
  - export PATH=$PATH:$HOME/.local/bin          # Ensure the virtual environment is in the PATH
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set default.region $AWS_DEFAULT_REGION
  - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $DOCKER_IMAGE_ECR
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

build:
  stage: build
  script:
    - source venv/bin/activate                  # Activate the virtual environment
    - echo "Building the Docker image..."
    - docker build -t $DOCKER_IMAGE_ECR:$CI_COMMIT_SHORT_SHA -t $DOCKER_IMAGE_DOCKER_HUB:$CI_COMMIT_SHORT_SHA -f Dockerfile .
    - docker tag $DOCKER_IMAGE_ECR:$CI_COMMIT_SHORT_SHA $DOCKER_IMAGE_ECR:latest
    - docker tag $DOCKER_IMAGE_DOCKER_HUB:$CI_COMMIT_SHORT_SHA $DOCKER_IMAGE_DOCKER_HUB:latest
    - docker save $DOCKER_IMAGE_ECR:$CI_COMMIT_SHORT_SHA -o $CI_COMMIT_SHORT_SHA.tar
  artifacts:
    paths:
      - $CI_COMMIT_SHORT_SHA.tar

deploy:
  stage: deploy
  script:
    - source venv/bin/activate                  # Activate the virtual environment
    - echo "Loading the Docker image..."
    - docker load -i $CI_COMMIT_SHORT_SHA.tar
    - echo "Deploying the Docker image to ECR..."
    - docker push $DOCKER_IMAGE_ECR:$CI_COMMIT_SHORT_SHA
    - docker push $DOCKER_IMAGE_ECR:latest
    - echo "Deploying the Docker image to Docker Hub..."
    - docker push $DOCKER_IMAGE_DOCKER_HUB:$CI_COMMIT_SHORT_SHA
    - docker push $DOCKER_IMAGE_DOCKER_HUB:latest
  dependencies:
    - build
  only:
    - main
